require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.2
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 200

RSpec/MultipleExpectations:
  Max: 4

Metrics/BlockLength:
  Max: 100
