language: ruby
dist: focal
before_install:
  - gem install --no-document rubocop
  - sudo service postgresql restart
  - sleep 1
  - postgres --version
rvm:
  - 3.0.2
before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rake ci:tests
addons:
  postgresql: '12'
  apt:
      packages:
        - postgresql-12
services:
  - postgresql
notifications:
  email: false