language: ruby
dist: focal
addons:
  postgresql: '12'
  apt:
      packages:
        - postgresql-12
env:
  global:
  - PGUSER=postgres
  - PGPORT=5432
  - PGHOST=localhost
before_install:
  - gem install --no-document rubocop
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - postgres --version
rvm:
  - 3.0.2
before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rake ci:tests
services:
  - postgresql
notifications:
  email: false